---
- name: co-hosting
  hosts: server1
  become: true
  
  vars_prompt:

    - name: uusername
      prompt: What is your username?
      private: no

    - name: upassword
      prompt: What is your password?
   
    - name: domain
      prompt: Enter the domain name
      private: no
  
 
  tasks: 
  - name: useradd
    user:
      name: "{{ uusername }}"
      password: "{{ ' upassword '   | password_hash('sha512') }}" 
      groups:
      state: present
      shell: /bin/bash
      system: no
      createhome: yes
      home: /var/www/html/{{ uusername }}
   
  - name: vhost creation
    template: 
       src: /root/vhost.conf.j2
       dest: /etc/httpd/conf.d/{{ uusername }}.conf
  - name: php configuration
    template:
       src: /root/php.conf.j2
       dest: /etc/php-fpm.d/{{ uusername }}.conf
  - name: check httpd
    command: httpd -t

  - name: check php
    command: php-fpm -t
  
  - name: reatart httpd
    service:
      name: httpd
      state: restarted
 
  - name: reatart php
    service:
      name: php-fpm
      state: restarted
